version: '3.4'
services:
  fe:
    build:
      context: .
      dockerfile: ./HelloStandardFE/Dockerfile
      network: host
    image: fe
    depends_on:
      - be
    ports:
      - "80:80"
    links:
      - be
  be:
    build:
      context: .
      dockerfile: ./HelloStandardBE/Dockerfile
      network: host
    image: be
    ports:
      - "5000:5000"
  be2:
    build:
      context: .
      dockerfile: ./HelloStandardBE/Dockerfile
      network: host
    image: be2
    ports:
      - "5001:5001"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  # This is for simulating the oracle database ... We will have to change out the JPA database type as an environment variable oracle/mysql
  # mysql:
  #   image: mysql
