version: '3.4'
services:
  fe:
    build:
      context: .
      dockerfile: ./HelloStandardFE/Dockerfile
      network: host
    image: fe
    depends_on:
      - be
    ports:
      - "8080:8080"
    links:
      - be
  be:
    build:
      context: .
      dockerfile: ./HelloStandardBE/Dockerfile
      network: host
    image: be
    ports:
      - "5000:5000"
  be2:
    build:
      context: .
      dockerfile: ./HelloStandardBE/Dockerfile
      network: host
    image: be2
    ports:
      - "5001:5001"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  mysql:
    image: mysql
